name: chatgpt
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  google_fonts: ^3.0.1
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.3
  dartdoc: ^6.1.5
  flutter_chat_types: ^3.6.0
  flutter_chat_ui: ^1.6.6
  flutter_gravatar: ^2.0.2
  flutter_markdown: ^0.6.13
  file_picker: ^5.2.5
  flutter_svg: ^1.1.6
  http: ^0.13.5
  image_picker: ^0.8.6
  mime: ^1.0.4
  provider: ^6.0.5
  uuid: ^3.0.7
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/

